import { 
  Plus, Trash2, Edit3, Save, X, Check, Search, Filter,
  ArrowUp, ArrowDown, ChevronLeft, ChevronRight, ChevronDown, ChevronUp,
  AlertTriangle, Info, CheckCircle2, XCircle, User, Settings,
  LogOut, Menu, Activity, Box, ShoppingCart, DollarSign,
  TrendingUp, TrendingDown, FileText, Printer, FileSpreadsheet, Eye, 
  EyeOff
} from 'lucide-react';

// Centralised icon export mapping for generic UI
export const Icons = {
  Add: Plus,
  Delete: Trash2,
  Edit: Edit3,
  Save: Save,
  Cancel: X,
  Confirm: Check,
  Search: Search,
  Filter: Filter,
  SortAsc: ArrowUp,
  SortDesc: ArrowDown,
  ArrowLeft: ChevronLeft,
  ArrowRight: ChevronRight,
  ArrowDown: ChevronDown,
  ArrowUpIcon: ChevronUp,
  Warning: AlertTriangle,
  Info: Info,
  Success: CheckCircle2,
  Error: XCircle,
  Account: User,
  Settings: Settings,
  LogOut: LogOut,
  Menu: Menu,
  Activity: Activity,
  Product: Box,
  Cart: ShoppingCart,
  Money: DollarSign,
  Revenue: TrendingUp,
  Expense: TrendingDown,
  Document: FileText,
  Print: Printer,
  Excel: FileSpreadsheet,
  Visible: Eye,
  Hidden: EyeOff,
};
